"""add market data candle uniqueness

Revision ID: d727d98a5812
Revises: 90f76bfe0a69
Create Date: 2026-09-24 13:03:41.164780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd727d98a5812'
down_revision: Union[str, Sequence[str], None] = '90f76bfe0a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_market_data_candle', 'market_data', ['symbol', 'timeframe', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_data_candle', 'market_data', type_='unique')
    # ### end Alembic commands ###
